FROM python:3.13-slim AS build

RUN apt update
RUN apt install -y python3-venv
RUN python3 -m venv /venv
RUN apt install -y npm curl
RUN npm i -g n
RUN n latest
RUN apt install -y make
RUN apt install -y python3-dev
COPY ./custom-elements /app/custom-elements
WORKDIR /app/custom-elements
RUN npm i
RUN apt-get update && apt-get install -y \
    libgtk-3-0 \
    libwebkit2gtk-4.1-0 \
    libglib2.0-0 \
    libgdk-pixbuf-2.0-0 \
    libpango-1.0-0 \
    libcairo2 \
    libx11-6 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libxtst6 \
    libnss3 \
    ca-certificates
RUN apt install -y cmake libcairo2-dev #libgirepository-2.0-dev
RUN apt install -y libgirepository-1.0-dev
#RUN pip install pycairo
RUN pip install pywebview[gtk]
WORKDIR /app
COPY ./build_requirements.txt /app/build_requirements.txt
RUN /venv/bin/pip install -r build_requirements.txt
COPY ./components.mk /app/components.mk
COPY ./packaging.mk /app/packaging.mk
COPY ./wheel.mk /app/wheel.mk
COPY ./Makefile /app/Makefile
COPY ./cython-compile.list /app/cython-compile.list
RUN make prepare-all
COPY ./pyproject.toml /app/pyproject.toml
COPY ./README.md /app/README.md
COPY ./src /app/src
RUN make build-wheel
RUN make package
RUN make package-python



FROM scratch AS export
COPY --from=build /app/untext /untext
COPY --from=build /app/untext-python /untext-python
